name: Test Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    # using a strategy matrix to test multiple Python versions in parallel
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} # running tests for each Python version

      # cache dependencies to speed up future runs
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # cache pip dependencies
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov  # Installing required dependencies manually

      # run tests & generate coverage report
      - name: Run Tests with Coverage
        run: pytest --cov=calc
